# Generated by Django 4.0.1 on 2022-01-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
