# Generated by Django 4.0.1 on 2022-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('password', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
